#!/usr/bin/env bash

cd /Users/lei.yang/lei-workspace/java/info-thread-api
mvn package
#mvn clean install
rm /usr/local/var/www/info-api/info-thread-api.war
cp /Users/lei.yang/lei-workspace/java/info-thread-api/target/info-threads-0.0.1-SNAPSHOT.war /usr/local/var/www/info-api/info-thread-api.war
java -jar /usr/local/var/www/info-api/info-thread-api.war
